### ISSUE TITLE
Cannot add tasks

### ISSUE THREAD

**Issue by Leif-Frederiksen** [s-KaiNet/vsts-pnp-powershell#1]
Hi, I have installed your extension, but I cannot add any tasks from it.
When browsing in tasks, it reports as "Installed" but there are no tasks with a "Add" button.
What am I missing?
![image](https://user-images.githubusercontent.com/25172917/49520462-981a0580-f8a3-11e8-8d3b-ba83bd271fce.png)

**Comment by s-KaiNet** [comment]
Hi, hmmmm the same for me... I will take a look.

**Comment by s-KaiNet** [comment]
Ok, just refresh the page, search it once again and the link should be available: 
![image](https://user-images.githubusercontent.com/10658276/49524201-61041e00-f8bc-11e8-87be-743a430021d6.png)

**Comment by Leif-Frederiksen** [comment]
Great, it works now. Thank you very much :-)
