### ISSUE TITLE
connect-pnponline fails

### ISSUE THREAD

**Issue by Leif-Frederiksen** [s-KaiNet/vsts-pnp-powershell#2]
Hi,

As of today my scripts using this Azure Devops step are starting to fail.
I get this error message: 
+ Connect-PnPOnline -Url $siteUrl -Credentials $cred
2019-02-12T09:05:54.0527513Z + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2019-02-12T09:05:54.0528050Z + CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], MissingMethodException
2019-02-12T09:05:54.0528424Z + FullyQualifiedErrorId : System.MissingMethodException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

I have noted that the step is pulling version 3.6.1902.0 of the PnP module:
Performing the operation "Install-Module" on target "Version '3.6.1902.0' of module 'SharePointPnPPowerShellOnline'".

If I rerun steps from previous days, then I can see that version 3.5.1901 was used - and these worked fine.

I tried downloading 3.6.1902.0 to my local PC and check if there was a problem with connect-pnponline, but that worked fine.

Can you help clear this up? Or can I force the step to download a specific version?

Regards
Leif

**Comment by s-KaiNet** [comment]
Hi, thanks for reporting,

they made PowerShell Core be the default version of PowerShell, which obviously doesn't work well with the current version of PnP-Powershell.    

I've made an update to make sure build step uses the correct version of PowerShell, could you please check if your issue is resolved?

**Comment by Leif-Frederiksen** [comment]
Hi Sergei,

It works like a dream now :-)

Thank you for fast response.

Regards
Leif

Den man. 18. feb. 2019 kl. 13.23 skrev Sergei Sergeev <
notifications@github.com>:

**Comment by s-KaiNet** [comment]
Cool! :)

**Comment by s-KaiNet** [comment]
@Leif-Frederiksen JFYI I've added version selection as well because always installing the latest version isn't a good idea. Added SharePoint environment selection as well, the default is Online, so it shouldn't break anything for you.

**Comment by Leif-Frederiksen** [comment]
That sounds great! Thanks a lot.

/Leif

Den tir. 19. feb. 2019 kl. 12.25 skrev Sergei Sergeev <
notifications@github.com>:

**Comment by Leif-Frederiksen** [comment]
Hi again Sergei,

Hi Sergei,
I have been using the PnP-Powershell task in my Azure devops release
pipelines for some years now.
For some reason it has just started to fail on the login:

Connect-PnPOnline : The sign-in name or password does not match one in the
Microsoft account system.

I have tried using the same credentials interactively, and they work fine.

Can you shed some light on what could be wrong and how to fix it?
I found this page that may give a clue, but it is for "raw" powershell:
https://areflyen.no/posts/2023-04-04-azure-devops-release-pipeline-with-pnp.powershell-fails/

Oh, and another thing: I think there is a problem with the "Contact" form
on your blog page (https://spblog.net/contact). When submitting something,
it just goes into "disabled" mode, and in the logs there are some errors
regarding some captcha thing:
[image: image.png]



Best regards
Leif

Den ons. 20. feb. 2019 kl. 12.25 skrev Leif Frederiksen <
***@***.***>:
