### ISSUE TITLE
Can't connect to Sharepoint Online site.

### ISSUE THREAD

**Issue by dmitrydyachenko** [s-KaiNet/vsts-pnp-powershell#4]
Hi Sergei,

I get an error when trying to connect to a Sharepoint Online site via Azure DevOps

![Screen Shot 2019-07-05 at 11 00 43](https://user-images.githubusercontent.com/18660673/60715299-99341380-9f14-11e9-82cc-5d56e126b956.png)

It happens only for some sites, for other it works well and I am able to connect.

The really weird thing is that it worked yesterday but today it stopped working.

Thank you for you help.

**Comment by s-KaiNet** [comment]
Hi Dima, 

Does it work without Azure DevOps, i.e. in a regular PS window?

**Comment by s-KaiNet** [comment]
Do you use PnP Provisioning via PnP PS and export a site using `Get-PnPProvisioningTemplate` or exporting a page?

**Comment by dmitrydyachenko** [comment]
I am using Azure DevOps -> Pipelines

![Screen Shot 2019-07-05 at 11 16 06](https://user-images.githubusercontent.com/18660673/60716037-5115f080-9f16-11e9-9177-944ad44653ab.png)

Sorry, didn't get the question: "Do you use PnP Provisioning via PnP PS and export a site using Get-PnPProvisioningTemplate or exporting a page?" - I am just trying to run some PowerShell commands using your task template.

**Comment by dmitrydyachenko** [comment]
> Hi Dima,
> 
> Does it work without Azure DevOps, i.e. in a regular PS window?

**Comment by s-KaiNet** [comment]
I meant do you use `Get-PnPProvisioningTemplate` commands inside your PS scripts or do you export SharePoint pages inside your PS scripts?

**Comment by s-KaiNet** [comment]
Also, have you recently changed the password you use for the task?
Sorry lots of questions :)

**Comment by dmitrydyachenko** [comment]
No, I don't. I am using: Get-PnPWeb, Add-PnPFile. I guess, I didn't even manage to connect to the site before using my PS scripts since the exception appears while connecting to the site but not in a script itself.

**Comment by dmitrydyachenko** [comment]
No worries, let me check my password.

**Comment by s-KaiNet** [comment]
> It happens only for some sites, for other it works well and I am able to connect.  

Does it mean, that the same user\password works for one site and doesn't work for another in the same tenant? In other words `Connect-PnPOnline` throws an exception for one site and works for others?

**Comment by dmitrydyachenko** [comment]
Well, yeah, I think I know what you mean: that something is wrong with the site itself. But this exception:` "The 'br' start tag on line 1 position 387 does not match the end tag of 'body'. Line 1, position"` looks really weird. Looks like while it's connecting to the site it gets some unusual response, kind of html.

**Comment by s-KaiNet** [comment]
Does it work without Azure DevOps, i.e. in a regular PS window?

**Comment by dmitrydyachenko** [comment]
I will check. One more question: is it possible to specify what PnP-PowerShell to install in your task template? 

UPD: Sorry, I have not noticed the field Version. Thank you!

**Comment by dmitrydyachenko** [comment]
Ok, I guess the error relates to MFA. Is there a way to use your task template with MFA enabled or are there any other ways to authenticate through SP Online sites?

**Comment by s-KaiNet** [comment]
Yes, you can create [an app password](https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords#create-and-delete-app-passwords-using-the-office-365-portal) and use it instead of your real password.

**Comment by s-KaiNet** [comment]
Closing as seems it's not relevant anymore.
