### ISSUE TITLE
MFA and Connect-PnPOnline

### ISSUE THREAD

**Issue by ShlokC** [s-KaiNet/vsts-pnp-powershell#5]
It is throwing below Connect-PnPOnline error if MFA is enabled on the site 
Connect-PnPOnline : Exception has been thrown by the target of an invocation.

 Connect-PnPOnline -Url $siteUrl -Credentials $cred
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CategoryInfo          : NotSpecified: (:) [Connect-PnPOnline], TargetInvocationException
FullyQualifiedErrorId : System.Reflection.TargetInvocationException,SharePointPnP.PowerShell.Commands.Base.ConnectOnline

**Comment by s-KaiNet** [comment]
For MFA enabled sites please use [App Passwords](https://support.office.com/en-gb/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183) instead of real passwords.
