### ISSUE TITLE
Cannot connect to SP Online from Azure DevOps

### ISSUE THREAD

**Issue by souravkar123** [s-KaiNet/vsts-pnp-powershell#6]
Cannot connect to SP Online from Azure DevOps. MFA enabled environment

![DevOps connectivity issue with SPO](https://user-images.githubusercontent.com/15612807/83818544-a104b680-a695-11ea-8939-55046ef53319.png)

**Comment by souravkar123** [comment]
![image](https://user-images.githubusercontent.com/15612807/83822105-22f8dd80-a69e-11ea-94bb-976988cf4b6f.png)

**Comment by s-KaiNet** [comment]
For MFA, please create a new [app password](https://docs.microsoft.com/en-us/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords#create-new-app-passwords) and use it instead of your real password.

**Comment by s-KaiNet** [comment]
Closing the issue, please reopen if you have more questions.
